NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="LUM Boutique"
ORG_URL="https://happymealtech.github.io/lum"
ORG_DESCRIPTION="Negozio di abbigliamento su blockchain Stellar. Qualità e trasparenza."

[[CURRENCIES]]
code="SCARPA"
issuer="GBB27IQBEUV4ID5HSGTQQIA4G4GCJMBEQBVVDC2ANTWVDGI6KI3QKVY"
display_decimals=0
name="Scarpa + Camicia"
desc="Set coordinato scarpa e camicia (200 unità disponibili)"
image="https://happymealtech.github.io/lum/assets/scarpa.jpg"

[[CURRENCIES]]
code="MAGLIONE"
issuer="GBB27IQBEUV4ID5HSGTQQIA4G4GCJMBEQBVVDC2ANTWVDGI6KI3QKVY"
display_decimals=0
name="Maglione G. Collo Rosa"
desc="Maglia rosa alta qualità (83 unità disponibili)"
image="https://happymealtech.github.io/lum/assets/maglione.jpg"

[[CURRENCIES]]
code="GIACCA"
issuer="GBB27IQBEUV4ID5HSGTQQIA4G4GCJMBEQBVVDC2ANTWVDGI6KI3QKVY"
display_decimals=0
name="Giacca Elegante"
desc="Taglio sartoriale (19 unità disponibili)"
image="https://happymealtech.github.io/lum/assets/giacca.jpg"

[[CURRENCIES]]
code="OROLOGIO"
issuer="GBB27IQBEUV4ID5HSGTQQIA4G4GCJMBEQBVVDC2ANTWVDGI6KI3QKVY"
display_decimals=0
name="Orologio Luxury"
desc="Edizione limitata (10 unità disponibili)"
image="https://happymealtech.github.io/lum/assets/orologio.jpg"
